[tool.black]
line-length = 88  # Set your desired line length
target-version = ['py310']  # Set your desired Python version
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.black.files]
# Add the paths to the Python files you want to format
paths = [
  "./app",
]
